services:
  flutter-builder:
    image: ghcr.io/royhomecontrol/flutter-builder:latest
    working_dir: /workspace
    volumes:
      - .:/workspace
      - flutter-pub-cache:/root/.pub-cache
      - gradle-cache:/root/.gradle
      - android-sdk:/android-sdk
      - flutter-cache:/flutter/bin/cache
      - ${DEPLOY_PATH}:/output
    
    command: bash /workspace/scripts/build.sh
  
volumes:
  flutter-pub-cache:
  gradle-cache:
  android-sdk:
  flutter-cache: