FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

# flutter APK 빌드를 위한 기본 패키지
RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    wget \
    vim \
    ca-certificates \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    openjdk-17-jdk \
    bash \
    && rm -rf /var/lib/apt/lists/*

ENV FLUTTER_HOME=/flutter
RUN git clone https://github.com/flutter/flutter.git -b stable $FLUTTER_HOME

ENV PATH="$FLUTTER_HOME/bin:$FLUTTER_HOME/bin/cache/dart-sdk/bin:$PATH"

# Android SDK (commandline tools)
ENV ANDROID_HOME=/android-sdk
RUN mkdir -p $ANDROID_HOME/cmdline-tools

RUN wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O tools.zip && \
    unzip tools.zip -d $ANDROID_HOME/cmdline-tools && \
    rm tools.zip

RUN mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

ENV PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# Android SDK 설치
RUN yes | sdkmanager --licenses || true && \
    sdkmanager "platform-tools" \
               "platforms;android-34" \
               "build-tools;34.0.0"

WORKDIR /workspace
