name: Build APK in Docker

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: self-hosted

        env:
            DEPLOY_PATH : "C:\\Users\\User\\Desktop\\MineCraft\\FileServer_For_Resourcepack\\files\\myhome"
            APP_NAME : "myhome"
        
        steps:
          - uses: actions/checkout@v4

          - name: Ensure deploy directory exists
            run: |
              if (-not (Test-Path "$env:DEPLOY_PATH")) {
                New-Item -ItemType Directory -Path "$env:DEPLOY_PATH" -Force
              }
            shell: powershell
          
          - name: Create Signing files
            shell: powershell
            run: |
              [IO.File]::WriteAllBytes(
                "android/myhome-release.keystore",
                [Convert]::FromBase64String("${{secrets.MYHOME_KEYSTORE}}")
              )

              @"
              storeFile=../myhome-release.keystore
              storePassword=${{secrets.STORE_PASSWORD}}
              keyPassword=${{secrets.KEY_PASSWORD}}
              keyAlias=${{secrets.KEY_ALIAS}}
              "@ | Out-File android/key.properties -Encoding ascii

              if (-not (Test-Path "android/myhome-release.keystore")) {
                Write-Host "Keystore file not found!"
                exit 1
              }
              if (-not (Test-Path "android/key.properties")) {
                Write-Host "Key properties file not found!"
                exit 1
              }
          
          - name: Create Stub Secret file
            shell: powershell
            run: |
              Copy-Item .\lib\core\secrets_example.dart .\lib\core\secrets.dart

          - name: Build Android APK
            env:
                COUCHDB_USER: ${{secrets.COUCHDB_USER}}
                COUCHDB_PASSWORD: ${{secrets.COUCHDB_PASSWORD}}
                IS_DEV: 'false'
            run:     docker compose -f builder.compose.yaml run -e COUCHDB_USER -e COUCHDB_PASSWORD -e IS_DEV --rm flutter-builder
            shell: powershell
        
          - name: Generate metadata
            run: |
              .\scripts\generate_metadata.ps1 `
                -BinaryPath "$env:DEPLOY_PATH\$env:APP_NAME.apk" `
                -DownloadBaseUrl "http://100.108.137.1:11096/download" `
                -OutputPath "$env:DEPLOY_PATH\metadata.json"
            shell: powershell

          - name: Print result
            run: |
              Write-Host "=== Deployed Files ==="
              Get-ChildItem "$env:DEPLOY_PATH"
              Write-Host "=== metadata.json content ==="
              Get-Content "$env:DEPLOY_PATH\metadata.json"
            shell: powershell